---
# tasks file for roles/docker_centos
- name: update all installed packages
  ansible.builtin.yum: 
    name: "*"
    state: "latest"
    update_cache: "yes"

- name: add gpg key for docker repo
  ansible.builtin.rpm_key:
    key: "{{ docker.gpg_key }}"
    state: present

- name: add docker repo
  ansible.builtin.get_url: 
    url: "{{ docker.repo_url }}"
    dest: "{{ docker.repo_path }}"
    mode: "0644"

- name: install docker packages
  ansible.builtin.yum: 
    name: "{{ item }}"
    state: "installed"
    update_cache: "yes"
  with_items: "{{ docker.packages }}"

- name: install pip
  ansible.builtin.easy_install:
    name: pip
    state: latest

- name: install python packages
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ docker.pip }}"

- name: put selinux into permissive mode
  ansible.builtin.selinux:
    policy: targeted
    state: permissive

- name: start docker and configure to start on boot
  ansible.builtin.service: 
    name: "docker"
    state: "started"
    enabled: "yes"